'use client';
import Image from 'next/image'
import janner from "../app/images/janner.png"
import graph from "../app/images/dataAnalysis.png"
import code from "../app/images/code.png"
import research from "../app/images/math.png"
import honors from "../app/images/honors.png"
// import resume from "../app/images/Zhanerke_Zhumash_Resume_2024.pdf";
// import { pdfjs } from 'react-pdf';
import {useTypewriter, Cursor, Typewriter} from 'react-simple-typewriter' 



import Head from 'next/head'

import {BsFillMoonStarsFill} from 'react-icons/bs'

import { AiFillGithub,  AiFillLinkedin } from "react-icons/ai";
import { RiGithubLine } from "react-icons/ri";

import Link from "next/link" 

import { useState } from "react"; 


export default function Home() {
  const [text] = useTypewriter({
    words: ['A Merit-Based International Scholar 🎓 @UBCV','An Ex-Developer 🌳  @ Emerging Media Lab', 'A Machine Learning Climate Researcher 🪸 @ UBCV', "A Co-Founder of Thread Exchange 🧶"],
    loop: {},
    typeSpeed: 48,
    deleteSpeed: 55, 
  })

  return (
    <div className=''> 
      <Head>
        <title> Zhanerke Zhumash</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=''>
       {/* Section 1 */}
       <section className=' h-screen min-h-screen'>


         {/* Paragraph about me */}
         <div className= "text-slate-300 font-mono text-center p-10">
           <h1 className='text-6xl py-3'> Janner (Zhanerke) Zhumash </h1>
           <h1 style={{margin:'50px'}} className='text-5xl'>
          
             I am {' '}
             <span style={{fontWeight:'bold', color: 'fuchsia'}}>
               { text}
             </span>
             <Cursor/>
           </h1>
          
           <h3 className='text-2xl'> BS in Applied Mathematics + Data science @ UBCV, Vancouver, Canada, BC</h3>
         </div>


      


         {/* Social links and icons */}
        
         <div className='text-5xl flex justify-center gap-16 '>
           <a href='https://github.com/zhvner'>
           <RiGithubLine className='fill-slate-300 '/>
           </a>


           <a href='https://www.linkedin.com/in/zhanerke-zhumash1/' target='_blank' rel='noopener noreferrer'>
             <AiFillLinkedin className='fill-slate-300' />
           </a>
         </div>


         {/* Circle with my profile picture */}


         <div className='relative mx-auto bg-gradient-to-b  from-cyan-700 to-fuchsia-600 rounded-full w-60 h-60 mt-10 overflow-hidden'>
           <Image src={janner} layout='fill' objectFit='cover' />


         </div>

         <div className='justify-center text-center p-10 font-mono  '>
           <h3 className=' text-3xl py-1 '>
             Things I enjoy
           </h3>
           <p className='text-md py-3 leading-7'>
             Hiking<span className='text-fuchsia-800'> • </span> Marathons <span className='text-fuchsia-800'> • </span> Snowboarding  <span className='text-fuchsia-800'> • </span>  Collaboration
           </p>
           <p className='text-md '>
             Wellness  <span className='text-fuchsia-800'> • </span> Taking pictures  <span className='text-fuchsia-800'> • </span> Reading 
           </p>
        
         </div>
         
       </section>


     {/* Section 2 */}
       <section className=' text-slate-300 font-mono md:shrink-0'>
         
        
         <div className='text-center'>
         <h3 className=' text-3xl py-1 '>
             Technical Interest Areas
           </h3>


         </div>
       {/* Card System of my projects*/}
         <div className='lg: flex gap-10 text-center'>
        
        
          
           <div className='bg-gray-800  text-center shadow-lg p-9 rounded-xl my-10'>
           <div className='flex justify-center'>
             <Image src={graph} width={100} height={100} />
           </div>
             <h3 className='text-lg font-medium pt-8 pb-2'>
               Mathematical animations. Art. Web Design.
             </h3>


             <h4 className='py-4 text-fuchsia-600'> Tech Stack </h4>
             <p className='py-1'> Python.  </p>
           </div>


           <div className='bg-gray-800  text-center shadow-lg p-9 rounded-xl my-10'>
           <div className='flex justify-center'>
             <Image src={research} width={100} height={100} />
           </div>
             <h3 className='text-lg font-medium pt-8 pb-2'>
               Research <span className='text-fuchsia-800'> • </span> Data Analysis <span className='text-fuchsia-800'> • </span>   Mathematical Modeling
             </h3>


             <h4 className='py-4 text-fuchsia-600'> Tech Stack </h4>
             <p className='py-1'> Python, R, MySQL</p>
           </div>


           <div className='bg-gray-800  text-center shadow-lg p-9 rounded-xl my-10'>
           <div className='flex justify-center'>
             <Image src={code} width={100} height={100} />
           </div>
             <h3 className='text-lg font-medium pt-8 pb-2'>
               Programming
             </h3>


             {/* <p className='py-2'>
               Software construction and web app developement
             </p> */}
             <h4 className='py-4 text-fuchsia-600'> Tech Stack </h4>
             <p className='py-1'> Java, Python, React, Flask, NoSQL(MongoDB)</p>
           </div>


           <div className='bg-gray-800  text-center shadow-lg p-9 rounded-xl my-10'>
           <div className='flex justify-center'>
             <Image src={honors} width={100} height={100} />
           </div>
             <h3 className='text-lg font-medium pt-8 pb-2'>
               Hackathons
             </h3>


             <p className='py-2'>
               Why? to develop technical and pitching skills at a soaring pace 👩🏻‍💻
             </p>
             <h4 className='py-4 text-fuchsia-600'> Tech Stack </h4>
             <p className='py-1'> Figma, React, Javascript, HTML, CSS</p>
           </div>
          
         </div>
        
       </section>




      


     </main>


      
    </div>
    
  )
}
